modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="stutterprotection"
version="3.0.0"
displayName="Stutter Protection"
description='''Protecting players when they suffer fps drops.'''
logoFile="icon.png"
authors="minhhjjj"

[[dependencies.stutterprotection]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.stutterprotection]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"